version: "3.9"

services:
  app:
    build:
      #현재 프로젝트의 Dockerfile 기반으로 Spring Boot 이미지 빌드
      context: .
      dockerfile: Dockerfile
    container_name: monew-app

    #호스트포트:컨테이너 포트
    #Dockerfile에서 --server.port=80으로 실행중이면 컨테이너 내부 포트는 80
    ports:
      - "${APP_PORT}:8080"
    environment:
      #application.yml의 spring.profiles.active 값을 덮어쓴다.(dev or prod)
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      #MongoDB, RDS 사용 -> 외부DB URI를 환경변수로 주입한다.
      MONGODB_URI: ${MONGODB_URI}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      NAVER_API_KEY: ${NAVER_API_KEY}
      NAVER_API_SECRET: ${NAVER_API_SECRET}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PRESIGNED_URL_EXPIRATION: ${AWS_S3_PRESIGNED_URL_EXPIRATION}

    # app이 비정상 종료되면 자동 재시작
    restart: unless-stopped