version: "3.9"

services:
  app:
    build:
      #현재 프로젝트의 Dockerfile 기반으로 Spring Boot 이미지 빌드
      context: .
      dockerfile: Dockerfile
    container_name: monew-app

    #PostgreSQL, MongoDB가 준비된 뒤 app 실행
    depends_on:
      db:
        condition: service_healthy    #db 컨테이너가 "헬스체크 통과" 상태일때 app실행
      mongodb:
        condition: service_healthy
      mongo-init:
        condition: service_completed_successfully

    #호스트포트:컨테이너 포트
    #Dockerfile에서 --server.port=80으로 실행중이면 컨테이너 내부 포트는 80
    ports:
      - "${APP_PORT}:80"
    environment:
      #application.yml의 spring.profiles.active 값을 덮어쓴다.(dev or prod)
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      #application-dev.yml의 MONGODB_URI 기본값은 localhost라서 컨테이너 환경에서는 덮어써야 함
      #mongodb는 아래 MongoDB 서비스명
      # replicaSet=rs0은 MongoDB 트랜잭션/replica set 사용을 위해 필요
      MONGODB_URI: mongodb://mongodb:27017/monew?replicaSet=rs0

      #app 컨테이너 내부에서는 localhost가 아니라 db 서비스명으로 접근해야한다.
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      NAVER_API_KEY: ${NAVER_API_KEY}
      NAVER_API_SECRET: ${NAVER_API_SECRET}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PRESIGNED_URL_EXPIRATION: ${AWS_S3_PRESIGNED_URL_EXPIRATION}

    # app이 비정상 종료되면 자동 재시작
    restart: unless-stopped