spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: monew
    password: monew123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/monew?replicaSet=rs0}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

logging:
  level:
    com.springboot.monew: INFO

springdoc:
  default-flat-param-object: true
