spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate    #DB랑 엔티티 구조 비교만하고 틀리면 에러
    properties:
      hibernate:
        format_sql: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

server:
  port: 80

logging:
  level:
    root: WARN
    com.springboot.monew: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
