spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        format_sql: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: WARN
    com.springboot.monew: INFO
