version: '3.8'

services:
  k6:
    image: grafana/k6:latest
    container_name: monew-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/test
    command: run /test/dist/main.js
